In [ ]:
print("hello world!")
print(589)

hello world!
589

In [ ]:
print("merhaba ben sena")

merhaba ben sena

In [ ]:
#Değişken oluşturma:= işareti ile oluştur
yas=21
isim= "sena"
print(yas)
print(isim)

21
sena

In [ ]:
benim_yaşım=21
favori_yiyeceğim="yaprak sarma"
print("ben" ,benim_yaşım, "yaşındayım ve sevdiğim yiyecek", favori_yiyeceğim , ".")

ben 21 yaşındayım ve sevdiğim yiyecek yaprak sarma .

In [ ]:
yiyecekler = [" fındıklı gofret" ,"elma" , "jelibon" , "patlamış mısır", "bezelye"]
print(yiyecekler)

[' fındıklı gofret', 'elma', 'jelibon', 'patlamış mısır', 'bezelye']

In [ ]:
ogrenci =["Marco", 22, "Ulysses", 19, "Sheila", 20]
print(ogrenci)

['Marco', 22, 'Ulysses', 19, 'Sheila', 20]

In [ ]:
len(yiyecekler)
print( "yiyecekler", len(yiyecekler) ,"tane yiyecek vardır.")

yiyecekler 5 tane yiyecek vardır.

kütüphaneleri tanıma

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
print("kütüphaneler başarı ile yüklendi")

kütüphaneler başarı ile yüklendi

In [16]:
df = pd.read_csv("Food_Dataset_Turkish (1).csv")
df.head(10)

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
0,Fındıklı Gofret,542,31.9,18.6,54.0,42.6,7.6,0.4,Tavsiye edilemez
1,Patlamış Mısır,499,23.0,13.8,57.0,3.8,10.7,1.8,Tavsiye edilemez
2,Elma,52,0.2,0.0,13.8,11.0,0.3,0.0,Tavsiye edilebilir
3,Çavdar Ekmeği,229,4.9,0.8,35.0,2.3,7.7,1.0,Tavsiye edilebilir
4,Muz,95,0.3,0.1,21.0,12.0,1.1,0.1,Tavsiye edilebilir
5,Patates Cipsi,503,28.0,2.6,53.0,2.9,6.3,2.8,Tavsiye edilemez
6,Çubuk Kraker,392,5.9,0.8,71.0,3.4,12.0,4.5,Tavsiye edilemez
7,Makarna,359,2.0,0.5,70.9,3.5,12.8,0.0,Tavsiye edilebilir
8,Patates Kızartması,289,14.0,1.3,36.0,0.3,3.4,0.7,Tavsiye edilemez
9,Bezelye,86,1.0,0.2,9.4,3.5,6.4,0.0,Tavsiye edilebilir

In [18]:
df.tail()

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
50,Bitter Çikolata,582,43.0,26.0,37.0,29.0,6.7,0.0,Tavsiye edilemez
51,Domates,19,0.1,0.0,3.5,3.2,0.7,0.0,Tavsiye edilebilir
52,Sandviç Bisküvi,470,18.5,8.6,68.7,32.4,5.4,0.4,Tavsiye edilemez
53,Karamelli Şeker,424,8.4,5.7,86.9,71.6,0.3,1.0,Tavsiye edilemez
54,Kabak,19,0.4,0.1,2.2,1.6,1.6,0.0,Tavsiye edilebilir

In [24]:
satır_sayısı = df.shape[0]
sutun_sayisi = df.shape[1]
print("bu tabloda" , satır_sayısı , "tane satır ve" , sutun_sayisi , "tane sütun vardır?" )

bu tabloda 55 tane satır ve 9 tane sütun vardır?

In [26]:
df["Öneri"].value_counts()

Öneri
Tavsiye edilemez      29
Tavsiye edilebilir    26
Name: count, dtype: int64

In [27]:
df.describe().round(1)

,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g)
count,55.0,55.0,55.0,55.0,55.0,55.0,55.0
mean,288.2,15.4,5.9,29.0,11.5,7.2,0.9
std,201.1,20.9,9.8,28.3,18.0,6.2,1.2
min,7.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,106.0,0.5,0.1,3.2,0.8,1.6,0.0
50%,279.0,7.3,1.5,18.0,2.3,6.4,0.3
75%,405.5,22.5,6.8,54.5,13.5,11.2,1.6
max,743.0,82.0,55.0,86.9,71.6,24.0,5.5

In [28]:
df.sort_values("Şeker (g)",ascending=False).head()

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
53,Karamelli Şeker,424,8.4,5.7,86.9,71.6,0.3,1.0,Tavsiye edilemez
31,Hurma,279,0.2,0.1,73.0,60.0,2.2,0.0,Tavsiye edilebilir
26,Sütlü Çikolata,530,29.5,17.5,58.5,57.5,6.6,0.2,Tavsiye edilemez
38,Ahududu Reçeli,223,0.2,0.0,52.2,51.7,0.7,0.0,Tavsiye edilemez
35,Jelibon,343,0.1,0.1,77.0,46.0,6.9,0.1,Tavsiye edilemez

In [30]:
df.sort_values("Yağ (g)",ascending=True).head()

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
10,Göbek Marul,7,0.0,0.0,0.7,0.7,0.5,0.0,Tavsiye edilebilir
20,Salatalık,12,0.1,0.0,3.6,1.7,0.7,0.0,Tavsiye edilebilir
25,Patates,71,0.1,0.0,15.0,0.8,1.7,2.0,Tavsiye edilebilir
35,Jelibon,343,0.1,0.1,77.0,46.0,6.9,0.1,Tavsiye edilemez
51,Domates,19,0.1,0.0,3.5,3.2,0.7,0.0,Tavsiye edilebilir

In [33]:
X = df.drop(columns=["Ürün Adı","Öneri"])
y= df["Öneri"]
print(X.head())
print("\n")
print(y.head())

   Enerji (kcal)  Yağ (g)  Doymuş Yağ (g)  Karbonhidrat (g)  Şeker (g)  \
0            542     31.9            18.6              54.0       42.6
1            499     23.0            13.8              57.0        3.8
2             52      0.2             0.0              13.8       11.0
3            229      4.9             0.8              35.0        2.3
4             95      0.3             0.1              21.0       12.0

   Protein (g)  Tuz (g)
0          7.6      0.4
1         10.7      1.8
2          0.3      0.0
3          7.7      1.0
4          1.1      0.1


0      Tavsiye edilemez
1      Tavsiye edilemez
2    Tavsiye edilebilir
3    Tavsiye edilebilir
4    Tavsiye edilebilir
Name: Öneri, dtype: object

In [34]:
X_egitim, X_test, y_egitim, y_test = train_test_split(X, y, test_size=0.2)
print(X_egitim.shape)
print(X_test.shape)
print(y_egitim.shape)
print(y_test.shape)

(44, 7)
(11, 7)
(44,)
(11,)