# Python İle Karar Ağacı Oluşturma
1. Ekrana yazı yazdırma

In [1]:
# print() ile ekrana yazı yazma
print("Hello World!")

Hello World!

In [2]:
print("Merhaba, ben Shana.")

Merhaba, ben Shana.

In [4]:
# Değişken oluşturma: = işareti ile oluşturma
yaş = 21
isim = "Shana"
print(yaş)
print(isim)

21
Shana

In [5]:
benim_yaşım = 21
favori_yiyecek = "tavuklu pilav"

print("Ben", benim_yaşım, "yaşındayım ve en sevdiğim yiyecek", favori_yiyecek)

Ben 21 yaşındayım ve en sevdiğim yiyecek tavuklu pilav

In [11]:
# Bir liste oluşturma: [] ile yazılır
yiyecekler = ["elma","fındıklı gofret","bezelye","jelibon","mısır"]
print(yiyecekler)

['elma', 'fındıklı gofret', 'bezelye', 'jelibon', 'mısır']

In [12]:
ogrenci = ["Marco", 22, "Ulysses", 19, "Sheila", 20]
print(ogrenci)

['Marco', 22, 'Ulysses', 19, 'Sheila', 20]

In [14]:
len(yiyecekler)
print("Yiyecekler listesinde", len(yiyecekler), "tane yiyecek vardır.")

Yiyecekler listesinde 5 tane yiyecek vardır.

# kütüphaneleri tanıma

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
print("Kütüphaneler başarı ile yüklendi.")

Kütüphaneler başarı ile yüklendi.

In [16]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [20]:
# veri okuma: df data frame'in kısaltması ve "tablo" demektir
df = pd.read_csv("Food_Dataset_Turkish.csv")

# veri setini ilk 5 satırına bakma
df.head(10)

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
0,Fındıklı Gofret,542,31.9,18.6,54.0,42.6,7.6,0.4,Tavsiye edilemez
1,Patlamış Mısır,499,23.0,13.8,57.0,3.8,10.7,1.8,Tavsiye edilemez
2,Elma,52,0.2,0.0,13.8,11.0,0.3,0.0,Tavsiye edilebilir
3,Çavdar Ekmeği,229,4.9,0.8,35.0,2.3,7.7,1.0,Tavsiye edilebilir
4,Muz,95,0.3,0.1,21.0,12.0,1.1,0.1,Tavsiye edilebilir
5,Patates Cipsi,503,28.0,2.6,53.0,2.9,6.3,2.8,Tavsiye edilemez
6,Çubuk Kraker,392,5.9,0.8,71.0,3.4,12.0,4.5,Tavsiye edilemez
7,Makarna,359,2.0,0.5,70.9,3.5,12.8,0.0,Tavsiye edilebilir
8,Patates Kızartması,289,14.0,1.3,36.0,0.3,3.4,0.7,Tavsiye edilemez
9,Bezelye,86,1.0,0.2,9.4,3.5,6.4,0.0,Tavsiye edilebilir

In [21]:
df.tail(15)

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
40,Pirinç,349,0.9,0.3,77.3,0.3,7.3,0.0,Tavsiye edilebilir
41,Balık Kroket,195,7.7,0.6,18.0,0.8,13.0,1.0,Tavsiye edilebilir
42,Havuç,31,0.2,0.1,4.7,4.6,0.9,0.0,Tavsiye edilebilir
43,Somun Ekmek,271,1.6,0.5,55.0,1.2,8.0,1.7,Tavsiye edilemez
44,Dolmalık Biber,43,0.5,0.0,6.4,6.4,1.3,0.2,Tavsiye edilebilir
45,Vegan Salam,345,33.0,23.0,5.8,1.6,5.7,1.6,Tavsiye edilemez
46,Fiyonk Kraker,295,5.4,0.3,51.0,2.7,8.9,2.1,Tavsiye edilemez
47,Kaşar Peyniri,345,33.0,23.0,5.8,1.6,5.7,1.6,Tavsiye edilebilir
48,Ketçap,101,0.5,0.1,20.0,19.0,1.7,1.8,Tavsiye edilemez
49,Margarin,720,80.0,23.0,0.0,0.0,0.0,0.2,Tavsiye edilemez
50,Bitter Çikolata,582,43.0,26.0,37.0,29.0,6.7,0.0,Tavsiye edilemez
51,Domates,19,0.1,0.0,3.5,3.2,0.7,0.0,Tavsiye edilebilir
52,Sandviç Bisküvi,470,18.5,8.6,68.7,32.4,5.4,0.4,Tavsiye edilemez
53,Karamelli Şeker,424,8.4,5.7,86.9,71.6,0.3,1.0,Tavsiye edilemez
54,Kabak,19,0.4,0.1,2.2,1.6,1.6,0.0,Tavsiye edilebilir

In [23]:
# veride kaç tane satır / sütün var?
satir_sayisi = df.shape[0]
sütun_sayisi = df.shape[1]

print("Bu tabloda", satir_sayisi, "tane satir ve", sütun_sayisi, "tane sütun vardır.")

Bu tabloda 55 tane satir ve 9 tane sütun vardır.

In [24]:
# Her sınıftan kaç tane var?
df["Öneri"].value_counts()

Öneri
Tavsiye edilemez      29
Tavsiye edilebilir    26
Name: count, dtype: int64

In [26]:
# sayısal özet oluşturma
df.describe().round(1)

,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g)
count,55.0,55.0,55.0,55.0,55.0,55.0,55.0
mean,288.2,15.4,5.9,29.0,11.5,7.2,0.9
std,201.1,20.9,9.8,28.3,18.0,6.2,1.2
min,7.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,106.0,0.5,0.1,3.2,0.8,1.6,0.0
50%,279.0,7.3,1.5,18.0,2.3,6.4,0.3
75%,405.5,22.5,6.8,54.5,13.5,11.2,1.6
max,743.0,82.0,55.0,86.9,71.6,24.0,5.5

In [29]:
# Şekere göre azalan sıralama
df.sort_values("Şeker (g)", ascending=False).head()

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
53,Karamelli Şeker,424,8.4,5.7,86.9,71.6,0.3,1.0,Tavsiye edilemez
31,Hurma,279,0.2,0.1,73.0,60.0,2.2,0.0,Tavsiye edilebilir
26,Sütlü Çikolata,530,29.5,17.5,58.5,57.5,6.6,0.2,Tavsiye edilemez
38,Ahududu Reçeli,223,0.2,0.0,52.2,51.7,0.7,0.0,Tavsiye edilemez
35,Jelibon,343,0.1,0.1,77.0,46.0,6.9,0.1,Tavsiye edilemez

In [30]:
# yağa göre artan sıralama
df.sort_values("Yağ (g)", ascending=True).head()

,Ürün Adı,Enerji (kcal),Yağ (g),Doymuş Yağ (g),Karbonhidrat (g),Şeker (g),Protein (g),Tuz (g),Öneri
10,Göbek Marul,7,0.0,0.0,0.7,0.7,0.5,0.0,Tavsiye edilebilir
20,Salatalık,12,0.1,0.0,3.6,1.7,0.7,0.0,Tavsiye edilebilir
25,Patates,71,0.1,0.0,15.0,0.8,1.7,2.0,Tavsiye edilebilir
35,Jelibon,343,0.1,0.1,77.0,46.0,6.9,0.1,Tavsiye edilemez
51,Domates,19,0.1,0.0,3.5,3.2,0.7,0.0,Tavsiye edilebilir

In [32]:
# özellikler (X) Ürün Adı ve Öneri dışındaki tüm sütunlar
X = df.drop(columns=["Ürün Adı", "Öneri"])

# Hedef değişken (Y) sadece Öneri sütunu
Y = df["Öneri"]

print(X.head())
print("\n")
print(Y.head().tolist())

   Enerji (kcal)  Yağ (g)  Doymuş Yağ (g)  Karbonhidrat (g)  Şeker (g)  \
0            542     31.9            18.6              54.0       42.6
1            499     23.0            13.8              57.0        3.8
2             52      0.2             0.0              13.8       11.0
3            229      4.9             0.8              35.0        2.3
4             95      0.3             0.1              21.0       12.0

   Protein (g)  Tuz (g)
0          7.6      0.4
1         10.7      1.8
2          0.3      0.0
3          7.7      1.0
4          1.1      0.1


['Tavsiye edilemez', 'Tavsiye edilemez', 'Tavsiye edilebilir', 'Tavsiye edilebilir', 'Tavsiye edilebilir']

In [36]:
# %80 ve %20 olarak veri setini ayırma
X_egitim, X_test, Y_egitim, Y_test = train_test_split(
    X, Y,
    test_size=0.2,         #%20si test veri seti olsun
    random_state = 42,     #aynı sonucu almak için
    stratify = Y,          #iki sınıftan da orantıl al
)

print("Eğitim veri seti büyüklüğü:", len(X_egitim), "yiyecek")
print("Eğitim veri seti büyüklüğü:", len(Y_egitim), "yiyecek")
print("\n")
print("Test veri seti büyüklüğü:", len(X_test), "yiyecek")
print("Test veri seti büyüklüğü:", len(Y_test), "yiyecek")

Eğitim veri seti büyüklüğü: 44 yiyecek
Eğitim veri seti büyüklüğü: 44 yiyecek


Test veri seti büyüklüğü: 11 yiyecek
Test veri seti büyüklüğü: 11 yiyecek